# Generated by Django 3.1.7 on 2021-03-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicname', models.CharField(max_length=20, verbose_name='никнейм')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('name', models.CharField(max_length=50, verbose_name='имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Tabletop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название стола')),
                ('description', models.TextField(verbose_name='описание стола')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='table.usr')),
                ('players', models.ManyToManyField(related_name='players', to='table.Usr')),
            ],
        ),
    ]
