# Generated by Django 3.1.7 on 2021-03-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletop',
            name='gameSystem',
            field=models.CharField(choices=[('HONEYHEIST', 'Honey heist'), ('CRASHPANDAS', 'Crash pandas')], default='HONEYHEIST', max_length=50, verbose_name='игровая система'),
        ),
    ]
